spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:appdb
 data:apoorva
email:lingarajapoorva@gmail.com
number:123455
what is your name
how are you 
what do you wnat 
`
